import Head from "next/head";
import Header from "../src/components/Header";
import Hero from "../src/components/Hero";
import WelcomeSection from "../src/components/WelcomeSection";
import Footer from "../src/components/Footer";
import HeroImage from "../src/components/HeroImage";
import Main from "../src/components/Main";

export default function Home() {
  return (
    <>
      <Head>
        <title>Landie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <Header />
        <WelcomeSection />
        <HeroImage />
      </Hero>
      <Main />
      <Footer />
    </>
  );
}
